name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          mkdir my-app
          cd my-app
          npm ci
      - name: Build the app
        run: |
          cd my-app
          npm run build
      - name: Run component tests
        run: |
          cd my-app
      - name: Start the app
        run: |
          cd my-app
          npm start &
          npx wait-on --timeout 60000
